var ROM_LIST = {
	'm1-ja': 	{crc:'0x282a5caa', game:CARD_MOTHER_1,	lang:LANG_JAPANESE,	author:'Nintendo',		baseRom:'m1-en', patchExt:'.zip', hasDoc:false},
	'm1-en': 	{crc:'0xf5ef5002', game:CARD_MOTHER_1,	lang:LANG_ENGLISH,	author:'Nintendo'},	
	'm1-enA': 	{crc:'0x7b1be8c2', game:CARD_MOTHER_1,	lang:LANG_ENGLISH,	author:'Nintendo',		baseRom:'m1-en', patchExt:'.zip', specialAltRom:'proto'},
	'm1-enB': 	{crc:'0xe4aa8122', game:CARD_MOTHER_1,	lang:LANG_ENGLISH,	author:'Nintendo',		baseRom:'m1-en', patchExt:'.zip', specialAltRom:'Zero'},
	'm1-esA22':	{crc:'0xd80e3217', game:CARD_MOTHER_1,	lang:LANG_SPANISH, 	author:'OAD',			baseRom:'m1-en', patchExt:'.zip', version:'2.2',	hasDoc:true, website:'https://www.romhacking.net/translations/1721/'},
	'm1-esB09':	{crc:'0x16e1e273', game:CARD_MOTHER_1,	lang:LANG_SPANISH,	author:'Jackic', 		baseRom:'m1-en', patchExt:'.zip', version:'0.99',	hasDoc:true, website:'https://www.romhacking.net/translations/5647/'},
	'm1-fr10':	{crc:'0xbd1f8687', game:CARD_MOTHER_1,	lang:LANG_FRENCH,	author:'Ridculle',		baseRom:'m1-en', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'https://traf.romhack.org/?p=patchs&pid=490'},
	'm1-pl10': 	{crc:'0x27cb7095', game:CARD_MOTHER_1,	lang:LANG_POLISH,	author:'Voxar', 		baseRom:'m1-en', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'https://www.romhacking.net/translations/5152/'},
	'm1-ru09': 	{crc:'0x03b08fa5', game:CARD_MOTHER_1,	lang:LANG_RUSSIAN,	author:'CHIEF-NET',		baseRom:'m1-en', patchExt:'.zip', version:'0.9',	hasDoc:true, website:'http://chief-net.ru/index.php?option=com_content&task=view&id=37'},
	
	'm2-ja': 	{crc:'0x2019fabe', game:CARD_MOTHER_2,	lang:LANG_JAPANESE,	author:'Nintendo',		baseRom:'m2-en', patchExt:'.zip',					hasDoc:false},
	'm2-de10':	{crc:'0x4491e7b1', game:CARD_MOTHER_2,	lang:LANG_GERMAN,	author:'GlostU/Mexos',	baseRom:'m2-en', patchExt:'.zip', version:'1.0',	hasDoc:false,website:'https://github.com/GlostU/EarthBound-dee-uebersetzung', oldVersionOf:'m2-de'},
	'm2-de12':	{crc:'0x886b49b0', game:CARD_MOTHER_2,	lang:LANG_GERMAN,	author:'GlostU/Mexos',	baseRom:'m2-en', patchExt:'.zip', version:'1.2',	hasDoc:true, website:'https://github.com/GlostU/EarthBound-dee-uebersetzung', oldVersionOf:'m2-de'},
	'm2-de121':	{crc:'0x05372649', game:CARD_MOTHER_2,	lang:LANG_GERMAN,	author:'GlostU/Mexos',	baseRom:'m2-en', patchExt:'.zip', version:'1.2.1',	hasDoc:true, website:'https://github.com/GlostU/EarthBound-dee-uebersetzung', oldVersionOf:'m2-de'},
	'm2-de122':	{crc:'0x536f12ed', game:CARD_MOTHER_2,	lang:LANG_GERMAN,	author:'GlostU/Mexos',	baseRom:'m2-en', patchExt:'.zip', version:'1.2.2',	hasDoc:true, website:'https://github.com/GlostU/EarthBound-dee-uebersetzung', oldVersionOf:'m2-de'},
	'm2-de123':	{crc:'0x3637e8e5', game:CARD_MOTHER_2,	lang:LANG_GERMAN,	author:'GlostU/Mexos',	baseRom:'m2-en', patchExt:'.zip', version:'1.2.3',	hasDoc:true, website:'https://github.com/GlostU/EarthBound-dee-uebersetzung', lastVersionOf:'m2-de'},
	'm2-en': 	{crc:'0xdc9bb451', game:CARD_MOTHER_2,	lang:LANG_ENGLISH,	author:'Nintendo'},
	'm2-enA': 	{crc:'0xaf607132', game:CARD_MOTHER_2,	lang:LANG_ENGLISH,	author:'Nintendo',		baseRom:'m2-en', patchExt:'.zip', specialAltRom:'w/header'},
	'm2-esA20':	{crc:'0x314a6267', game:CARD_MOTHER_2,	lang:LANG_SP_LATINO,author:'ShadowOne333',	baseRom:'m2-en', patchExt:'.zip', version:'2.0',	hasDoc:false, website:'https://forum.starmen.net/forum/Community/PKHack/EarthBound-Spanish-translation/page/1/', oldVersionOf:'m2-esA'},
	'm2-esA33a':{crc:'0x426b0848', game:CARD_MOTHER_2,	lang:LANG_SP_LATINO,author:'ShadowOne333',	baseRom:'m2-en', patchExt:'.zip', version:'3.3.3 Oct. 2016',hasDoc:false, website:'https://forum.starmen.net/forum/Community/PKHack/EarthBound-Spanish-translation/page/1/', oldVersionOf:'m2-esA'},
	'm2-esA33b':{crc:'0xc46296ba', game:CARD_MOTHER_2,	lang:LANG_SP_LATINO,author:'ShadowOne333',	baseRom:'m2-en', patchExt:'.zip', version:'3.3.3 Jan. 2018',hasDoc:false, website:'https://forum.starmen.net/forum/Community/PKHack/EarthBound-Spanish-translation/page/1/', oldVersionOf:'m2-esA'},
	'm2-esA40':	{crc:'0x162b874c', game:CARD_MOTHER_2,	lang:LANG_SP_LATINO,author:'ShadowOne333',	baseRom:'m2-en', patchExt:'.zip', version:'4.0',	hasDoc:false, website:'https://www.romhacking.net/translations/2538/', lastVersionOf:'m2-esA'},
	'm2-esB10a':{crc:'0xbba9c81a', game:CARD_MOTHER_2,	lang:LANG_SP_SPAIN,	author:'josete2k',		baseRom:'m2-en', patchExt:'.zip', version:'1.0a',	hasDoc:true, website:'https://www.romhacking.net/translations/2638/'},
	'm2-fr11':	{crc:'0x87da4ebc', game:CARD_MOTHER_2,	lang:LANG_FRENCH,	author:'Team MAMBO',	baseRom:'m2-en', patchExt:'.zip', version:'1.1',	hasDoc:true},
	'm2-itA10':	{crc:'0x82bde573', game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'CRefice',		baseRom:'m2-en', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'https://forum.starmen.net/forum/Games/Mother3FanTranslation/EarthBound-Italian-Translation-COMPLETED', oldVersionOf:'m2-itA'},
	'm2-itA11':	{crc:'0xce1cecf9', game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'CRefice',		baseRom:'m2-en', patchExt:'.zip', version:'1.1',	hasDoc:true, website:'https://forum.starmen.net/forum/Games/Mother3FanTranslation/EarthBound-Italian-Translation-COMPLETED', lastVersionOf:'m2-itA'},
	'm2-itB10':	{crc:'0x46e3ccf2', game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'Vecna', 		baseRom:'m2-en', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'https://romhacking.it/project/view/id/646', oldVersionOf:'m2-itB'},
	'm2-itB11':	{crc:'0xe5313a7b', game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'Vecna', 		baseRom:'m2-en', patchExt:'.zip', version:'1.1',	hasDoc:true, website:'https://romhacking.it/project/view/id/646', oldVersionOf:'m2-itB'},
	'm2-itB12':	{crc:'0x4eada49f', game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'Vecna', 		baseRom:'m2-en', patchExt:'.zip', version:'1.2',	hasDoc:true, website:'https://romhacking.it/project/view/id/646', oldVersionOf:'m2-itB'},
	'm2-itB13':	{crc:'0x2de374fa', game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'Vecna', 		baseRom:'m2-en', patchExt:'.zip', version:'1.3',	hasDoc:true, website:'https://romhacking.it/project/view/id/646', oldVersionOf:'m2-itB'},
	'm2-itB145':{crc:'0xa7079c7a', game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'Vecna',			baseRom:'m2-en', patchExt:'.zip', version:'1.45',	hasDoc:true, website:'https://romhacking.it/project/view/id/646', oldVersionOf:'m2-itB'},
	'm2-itB146':{crc:'0xe6dbb3e6', game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'Vecna',			baseRom:'m2-en', patchExt:'.zip', version:'1.46',	hasDoc:true, website:'https://romhacking.it/project/view/id/646', oldVersionOf:'m2-itB'},
	'm2-itB147':{crc:'0x62c04f3f', game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'Vecna',			baseRom:'m2-en', patchExt:'.zip', version:'1.47',	hasDoc:true, website:'https://romhacking.it/project/view/id/646', lastVersionOf:'m2-itB'},
	'm2-pl100':	{crc:'0xf693cf87', game:CARD_MOTHER_2,	lang:LANG_POLISH,	author:'Voxar',			baseRom:'m2-en', patchExt:'.zip', version:'1.0.0',	hasDoc:true, website:'https://www.romhacking.net/translations/5600/', oldVersionOf:'m2-pl'},
	'm2-pl102':	{crc:'0xf31c0606', game:CARD_MOTHER_2,	lang:LANG_POLISH,	author:'Voxar', 		baseRom:'m2-en', patchExt:'.zip', version:'1.0.2',	hasDoc:true, website:'https://www.romhacking.net/translations/5600/', lastVersionOf:'m2-pl'},
	'm2-pt10': 	{crc:'0xa19f1c1c', game:CARD_MOTHER_2,	lang:LANG_PT_PORTUG,author:'EarthBound Brasil',baseRom:'m2-en',patchExt:'.zip',version:'1.0',	hasDoc:true, website:'https://www.earthboundbrasil.com'},
	
	'm12-ja':	{crc:'0x0a44569c', game:CARD_MOTHER_1_2,lang:LANG_JAPANESE,	author:'Nintendo'},
	'm12-ko11':	{crc:'0xc0cf1f7e', game:CARD_MOTHER_1_2,lang:LANG_KOREAN,	author:'아루미 & pjs',		baseRom:'m12-ja', patchExt:'.zip', version:'1.1',	hasDoc:true, website:'https://blog.naver.com/pjs0493/220591359815'},
	'm12-de10':	{crc:'0x61a57a10', game:CARD_MOTHER_1_2,lang:LANG_GERMAN,	author:'domflo', 		baseRom:'m12-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'https://youtube.com/domflo95'},
	'm12-en101':{crc:'0x7b1ff152', game:CARD_MOTHER_1_2,lang:LANG_ENGLISH,	author:'Tomato',		baseRom:'m12-ja', patchExt:'.zip', version:'1.0.1',	hasDoc:true, website:'http://mother12.earthboundcentral.com/'},
	'm12-fr10':	{crc:'0x4f5af1e5', game:CARD_MOTHER_1_2,lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m12-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'http://mother1vf.free.fr'},
	'm12-it10':	{crc:'0x1e7ab616', game:CARD_MOTHER_1_2,lang:LANG_ITALIAN,	author:'SilverM',		baseRom:'m12-ja', patchExt:'.zip', version:'1.0',	hasDoc:true},
	'm12-pt10':	{crc:'0x3be388bf', game:CARD_MOTHER_1_2,lang:LANG_PT_PORTUG,author:'Earthbound Brasil',baseRom:'m12-ja',patchExt:'.zip',version:'1.0',	hasDoc:true, website:'https://www.earthboundbrasil.com'},
	
	'm3-ja':	{crc:'0x42ac9cb9', game:CARD_MOTHER_3,	lang:LANG_JAPANESE,	author:'Nintendo'},
	'm3-zh10':	{crc:'0x21fdf96c', game:CARD_MOTHER_3,	lang:LANG_CHINESE,	author:'漫游汉化组',		baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'http://www.manyoteam.com/?p=32',		oldVersionOf:'m3-zh'},
	'm3-zh10f':	{crc:'0xe2447179', game:CARD_MOTHER_3,	lang:LANG_CHINESE,	author:'漫游汉化组',		baseRom:'m3-ja', patchExt:'.zip', version:'1.0+fix',hasDoc:true, website:'https://tieba.baidu.com/p/7313315937',lastVersionOf:'m3-zh'},
	'm3-ko10':	{crc:'0x58f58635', game:CARD_MOTHER_3,	lang:LANG_KOREAN,	author:'pjs',			baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:false,website:'http://blog.naver.com/pjs0493/220392308242'},
	'm3-de10':	{crc:'0x9163f829', game:CARD_MOTHER_3,	lang:LANG_GERMAN,	author:'Madokami',		baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'https://github.com/Madokamiiiiii/Mother3German/releases', oldVersionOf:'m3-de'},
	'm3-de11':	{crc:'0xb0b73624', game:CARD_MOTHER_3,	lang:LANG_GERMAN,	author:'Madokami',		baseRom:'m3-ja', patchExt:'.zip', version:'1.1',	hasDoc:true, website:'https://github.com/Madokamiiiiii/Mother3German/releases', lastVersionOf:'m3-de'},
	'm3-en10':	{crc:'0xd7a5322d', game:CARD_MOTHER_3,	lang:LANG_ENGLISH,	author:'Tomato',		baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'http://mother3.fobby.net/',	oldVersionOf:'m3-en'},
	'm3-en11':	{crc:'0xede46930', game:CARD_MOTHER_3,	lang:LANG_ENGLISH,	author:'Tomato',		baseRom:'m3-ja', patchExt:'.zip', version:'1.1',	hasDoc:true, website:'http://mother3.fobby.net/',	oldVersionOf:'m3-en'},
	'm3-en12':	{crc:'0xa323c029', game:CARD_MOTHER_3,	lang:LANG_ENGLISH,	author:'Tomato',		baseRom:'m3-ja', patchExt:'.zip', version:'1.2',	hasDoc:true, website:'http://mother3.fobby.net/',	oldVersionOf:'m3-en'},
	'm3-en13':	{crc:'0x8A3BC5A8', game:CARD_MOTHER_3,	lang:LANG_ENGLISH,	author:'Tomato',		baseRom:'m3-ja', patchExt:'.zip', version:'1.3',	hasDoc:true, website:'http://mother3.fobby.net/',	lastVersionOf:'m3-en'},
	'm3-en13f':	{crc:'0x0e013b7b', game:CARD_MOTHER_3,	lang:LANG_ENGLISH,	author:'Tomato',		baseRom:'m3-ja', patchExt:'.zip', version:'1.3+fix',hasDoc:true, website:'https://github.com/Lorenzooone/M3_Eng_1_3/releases', lastVersionOf:'m3-en'},
	'm3-es10':	{crc:'0x75a955a1', game:CARD_MOTHER_3,	lang:LANG_SPANISH,	author:'Jimmytrius',	baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'http://mother3spanish.blogspot.com/'},
	'm3-fr10':	{crc:'0xc0cdfcf5', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'http://mother3vf.free.fr/',	oldVersionOf:'m3-fr'},
	'm3-fr11':	{crc:'0x72000342', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.1',	hasDoc:true, website:'http://mother3vf.free.fr/',	oldVersionOf:'m3-fr'},
	'm3-fr12':	{crc:'0x102d3858', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.2',	hasDoc:true, website:'http://mother3vf.free.fr/',	oldVersionOf:'m3-fr'},
	'm3-fr13':	{crc:'0xd6ce8284', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.3',	hasDoc:true, website:'http://mother3vf.free.fr/',	oldVersionOf:'m3-fr'},
	'm3-fr14':	{crc:'0x1ac32422', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.4',	hasDoc:true, website:'http://mother3vf.free.fr/',	oldVersionOf:'m3-fr'},
	'm3-fr15':	{crc:'0x0d640e05', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.5',	hasDoc:true, website:'http://mother3vf.free.fr/',	oldVersionOf:'m3-fr'},
	'm3-fr16':	{crc:'0x733bc3e5', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.6',	hasDoc:true, website:'http://mother3vf.free.fr/',	oldVersionOf:'m3-fr'},
	'm3-fr17':	{crc:'0x65011f4a', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.7',	hasDoc:true, website:'http://mother3vf.free.fr/',	oldVersionOf:'m3-fr'},
	'm3-fr18':	{crc:'0x76df5b60', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.8',	hasDoc:true, website:'http://mother3vf.free.fr/',	oldVersionOf:'m3-fr'},
	'm3-fr19':	{crc:'0x81429453', game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',		baseRom:'m3-ja', patchExt:'.zip', version:'1.9',	hasDoc:true, website:'http://mother3vf.free.fr/',	lastVersionOf:'m3-fr'},
	'm3-itA10':	{crc:'0xec703e38', game:CARD_MOTHER_3,	lang:LANG_ITALIAN,	author:'Lorenzooone',	baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'https://www.romhacking.net/translations/2473/', oldVersionOf:'m3-itA'},
	'm3-itA11':	{crc:'0x58647a26', game:CARD_MOTHER_3,	lang:LANG_ITALIAN,	author:'Lorenzooone',	baseRom:'m3-ja', patchExt:'.zip', version:'1.1',	hasDoc:true, website:'https://www.romhacking.net/translations/2473/', oldVersionOf:'m3-itA'},
	'm3-itA111':{crc:'0xe7185f88', game:CARD_MOTHER_3,	lang:LANG_ITALIAN,	author:'Lorenzooone',	baseRom:'m3-ja', patchExt:'.zip', version:'1.1.1',	hasDoc:true, website:'https://www.romhacking.net/translations/2473/', lastVersionOf:'m3-itA'},
	'm3-itB10':	{crc:'0x7dfea226', game:CARD_MOTHER_3,	lang:LANG_ITALIAN,	author:'Snifit', 		baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'http://snifit.altervista.org/'},
	'm3-nl10':	{crc:'0x8b74324c', game:CARD_MOTHER_3,	lang:LANG_DUTCH,	author:'PrismaticAngel',baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'https://www.romhacking.net/translations/5722/'},
	'm3-pl10':	{crc:'0xe5911653', game:CARD_MOTHER_3,	lang:LANG_POLISH,	author:'Voxar',			baseRom:'m3-ja', patchExt:'.zip', version:'1.0',	hasDoc:true, website:'https://www.romhacking.net/translations/6161/'},
	'm3-pt10':	{crc:'0x00508b53', game:CARD_MOTHER_3,	lang:LANG_PT_PORTUG,author:'Earthbound Brasil',baseRom:'m3-ja',patchExt:'.zip',version:'1.0', 	hasDoc:true, website:'https://www.earthboundbrasil.com'},
}

/*var PROJECTS_LIST = {
	'm1-ja':	{game:CARD_MOTHER_1,	lang:LANG_JAPANESE,	author:'Nintendo',			baseRom:'m1-en'},
	'm1-en':	{game:CARD_MOTHER_1,	lang:LANG_ENGLISH,	author:'Nintendo'},
	'm1-enA':	{game:CARD_MOTHER_1,	lang:LANG_ENGLISH,	author:'Nintendo',			baseRom:'m1-en',	specialAltRom:'proto'},
	'm1-enB':	{game:CARD_MOTHER_1,	lang:LANG_ENGLISH,	author:'Nintendo',			baseRom:'m1-en',	specialAltRom:'Zero'},
	'm1-esA':	{game:CARD_MOTHER_1,	lang:LANG_SPANISH, 	author:'OAD',				baseRom:'m1-en',	website:'https://www.romhacking.net/translations/1721/'},
	'm1-esB':	{game:CARD_MOTHER_1,	lang:LANG_SPANISH,	author:'Jackic', 			baseRom:'m1-en',	website:'https://www.romhacking.net/translations/5647/'},
	'm1-fr':	{game:CARD_MOTHER_1,	lang:LANG_FRENCH,	author:'Ridculle',			baseRom:'m1-en',	website:'https://traf.romhack.org/?p=patchs&pid=490'},
	'm1-pl': 	{game:CARD_MOTHER_1,	lang:LANG_POLISH,	author:'Voxar', 			baseRom:'m1-en',	website:'https://www.romhacking.net/translations/5152/'},
	'm1-ru': 	{game:CARD_MOTHER_1,	lang:LANG_RUSSIAN,	author:'CHIEF-NET',			baseRom:'m1-en',	website:'http://chief-net.ru/index.php?option=com_content&task=view&id=37'},

	'm2-ja': 	{game:CARD_MOTHER_2,	lang:LANG_JAPANESE,	author:'Nintendo',			baseRom:'m2-en'},
	'm2-de':	{game:CARD_MOTHER_2,	lang:LANG_GERMAN,	author:'GlostU/Mexos',		baseRom:'m2-en',	website:'https://github.com/GlostU/EarthBound-dee-uebersetzung'},
	'm2-en': 	{game:CARD_MOTHER_2,	lang:LANG_ENGLISH,	author:'Nintendo'},
	'm2-enA': 	{game:CARD_MOTHER_2,	lang:LANG_ENGLISH,	author:'Nintendo',			baseRom:'m2-en',	specialAltRom:'w/header'},
	'm2-esA':	{game:CARD_MOTHER_2,	lang:LANG_SP_LATINO,author:'ShadowOne333',		baseRom:'m2-en',	website:'https://www.romhacking.net/translations/2538/'},
	'm2-esB':	{game:CARD_MOTHER_2,	lang:LANG_SP_SPAIN,	author:'josete2k',			baseRom:'m2-en',	website:'https://www.romhacking.net/translations/2638/'},
	'm2-fr':	{game:CARD_MOTHER_2,	lang:LANG_FRENCH,	author:'Team MAMBO',		baseRom:'m2-en'},
	'm2-itA':	{game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'CRefice',			baseRom:'m2-en',	website:'https://forum.starmen.net/forum/Games/Mother3FanTranslation/EarthBound-Italian-Translation-COMPLETED'},
	'm2-itB':	{game:CARD_MOTHER_2,	lang:LANG_ITALIAN,	author:'Vecna',				baseRom:'m2-en',	website:'https://romhacking.it/project/view/id/646'},
	'm2-pl':	{game:CARD_MOTHER_2,	lang:LANG_POLISH,	author:'Voxar',				baseRom:'m2-en',	website:'https://www.romhacking.net/translations/5600/'},
	'm2-pt': 	{game:CARD_MOTHER_2,	lang:LANG_PT_PORTUG,author:'EarthBound Brasil',	baseRom:'m2-en',	website:'https://www.earthboundbrasil.com'},
	
	'm12-ja':	{game:CARD_MOTHER_1_2,	lang:LANG_JAPANESE,	author:'Nintendo'},
	'm12-ko':	{game:CARD_MOTHER_1_2,	lang:LANG_KOREAN,	author:'아루미 & pjs',			baseRom:'m12-ja',	website:'https://blog.naver.com/pjs0493/220591359815'},
	'm12-de':	{game:CARD_MOTHER_1_2,	lang:LANG_GERMAN,	author:'domflo', 			baseRom:'m12-ja',	website:'https://youtube.com/domflo95'},
	'm12-en':	{game:CARD_MOTHER_1_2,	lang:LANG_ENGLISH,	author:'Tomato',			baseRom:'m12-ja',	website:'http://mother12.earthboundcentral.com/'},
	'm12-fr':	{game:CARD_MOTHER_1_2,	lang:LANG_FRENCH,	author:'MotherVF',			baseRom:'m12-ja',	website:'http://mother1vf.free.fr'},
	'm12-it':	{game:CARD_MOTHER_1_2,	lang:LANG_ITALIAN,	author:'SilverM',			baseRom:'m12-ja'},
	'm12-pt':	{game:CARD_MOTHER_1_2,	lang:LANG_PT_PORTUG,author:'Earthbound Brasil',	baseRom:'m12-ja',	website:'https://www.earthboundbrasil.com'},
	
	'm3-ja':	{game:CARD_MOTHER_3,	lang:LANG_JAPANESE,	author:'Nintendo'},
	'm3-zh':	{game:CARD_MOTHER_3,	lang:LANG_CHINESE,	author:'漫游汉化组',			baseRom:'m3-ja',	website:'http://www.manyoteam.com/?p=32'},
	'm3-ko':	{game:CARD_MOTHER_3,	lang:LANG_KOREAN,	author:'pjs',				baseRom:'m3-ja',	website:'http://blog.naver.com/pjs0493/220392308242'},
	'm3-de':	{game:CARD_MOTHER_3,	lang:LANG_GERMAN,	author:'Madokami',			baseRom:'m3-ja',	website:'https://github.com/Madokamiiiiii/Mother3German/releases'},
	'm3-en':	{game:CARD_MOTHER_3,	lang:LANG_ENGLISH,	author:'Tomato',			baseRom:'m3-ja',	website:'http://mother3.fobby.net/'},
	'm3-es':	{game:CARD_MOTHER_3,	lang:LANG_SPANISH,	author:'Jimmytrius',		baseRom:'m3-ja',	website:'http://mother3spanish.blogspot.com/'},
	'm3-fr':	{game:CARD_MOTHER_3,	lang:LANG_FRENCH,	author:'MotherVF',			baseRom:'m3-ja',	website:'http://mother3vf.free.fr/'},
	'm3-itA':	{game:CARD_MOTHER_3,	lang:LANG_ITALIAN,	author:'Lorenzooone',		baseRom:'m3-ja',	website:'https://www.romhacking.net/translations/2473/'},
	'm3-itB':	{game:CARD_MOTHER_3,	lang:LANG_ITALIAN,	author:'Snifit', 			baseRom:'m3-ja',	website:'http://snifit.altervista.org/'},
	'm3-nl':	{game:CARD_MOTHER_3,	lang:LANG_DUTCH,	author:'PrismaticAngel',	baseRom:'m3-ja',	website:'https://www.romhacking.net/translations/5722/'},
	'm3-pl':	{game:CARD_MOTHER_3,	lang:LANG_POLISH,	author:'Voxar',				baseRom:'m3-ja',	website:'https://www.romhacking.net/translations/6161/'},
	'm3-pt':	{game:CARD_MOTHER_3,	lang:LANG_PT_PORTUG,author:'Earthbound Brasil',	baseRom:'m3-ja',	website:'https://www.earthboundbrasil.com'},
};


var VERSIONS_LIST = {
	'm1-ja': 	{crc:'0x282a5caa',	projectId:'m1-ja',	patchExt:'.zip', hasDoc:false},
	'm1-en': 	{crc:'0xf5ef5002',	projectId:'m1-en'},
	'm1-enA': 	{crc:'0x7b1be8c2',	projectId:'m1-enA',	patchExt:'.zip', specialAltRom:'proto'},
	'm1-enB': 	{crc:'0xe4aa8122',	projectId:'m1-enB',	patchExt:'.zip', specialAltRom:'Zero'},
	'm1-esA22':	{crc:'0xd80e3217',	projectId:'m1-esA',	patchExt:'.zip', hasDoc:true,	version:'2.2'},
	'm1-esB09':	{crc:'0x16e1e273',	projectId:'m1-esB',	patchExt:'.zip', hasDoc:true,	version:'0.99'},
	'm1-fr10':	{crc:'0xbd1f8687',	projectId:'m1-fr',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm1-pl10': 	{crc:'0x27cb7095',	projectId:'m1-pl',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm1-ru09': 	{crc:'0x03b08fa5',	projectId:'m1-ru',	patchExt:'.zip', hasDoc:true,	version:'0.9'},
		
	'm2-ja': 	{crc:'0x2019fabe',	projectId:'m2-ja',	patchExt:'.zip', hasDoc:false},
	'm2-de10':	{crc:'0x4491e7b1',	projectId:'m2-de',	patchExt:'.zip', hasDoc:false,	version:'1.0'},
	'm2-de12':	{crc:'0x886b49b0',	projectId:'m2-de',	patchExt:'.zip', hasDoc:true,	version:'1.2'},
	'm2-de121':	{crc:'0x05372649',	projectId:'m2-de',	patchExt:'.zip', hasDoc:true,	version:'1.2.1'},
	'm2-de122':	{crc:'0x536f12ed',	projectId:'m2-de',	patchExt:'.zip', hasDoc:true,	version:'1.2.2'},
	'm2-de123':	{crc:'0x3637e8e5',	projectId:'m2-de',	patchExt:'.zip', hasDoc:true,	version:'1.2.3', lastVersion:true},
	'm2-en': 	{crc:'0xdc9bb451',	projectId:'m2-en'},
	'm2-enA': 	{crc:'0xaf607132',	projectId:'m2-esA',	patchExt:'.zip', specialAltRom:'w/header'},
	'm2-esA20':	{crc:'0x314a6267',	projectId:'m2-esA',	patchExt:'.zip', hasDoc:false,	version:'2.0', website:'https://forum.starmen.net/forum/Community/PKHack/EarthBound-Spanish-translation/page/1/'},
	'm2-esA33a':{crc:'0x426b0848',	projectId:'m2-esA',	patchExt:'.zip', hasDoc:false,	version:'3.3.3 Oct. 2016', website:'https://forum.starmen.net/forum/Community/PKHack/EarthBound-Spanish-translation/page/1/'},
	'm2-esA33b':{crc:'0xc46296ba',	projectId:'m2-esA',	patchExt:'.zip', hasDoc:false,	version:'3.3.3 Jan. 2018', website:'https://forum.starmen.net/forum/Community/PKHack/EarthBound-Spanish-translation/page/1/'},
	'm2-esA40':	{crc:'0x162b874c',	projectId:'m2-esA',	patchExt:'.zip', hasDoc:false,	version:'4.0', lastVersion:true},
	'm2-esB10a':{crc:'0xbba9c81a',	projectId:'m2-esB',	patchExt:'.zip', hasDoc:true,	version:'1.0a'},
	'm2-fr11':	{crc:'0x87da4ebc',	projectId:'m2-fr',	patchExt:'.zip', hasDoc:true,	version:'1.1'},
	'm2-itA10':	{crc:'0x82bde573',	projectId:'m2-itA',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm2-itA11':	{crc:'0xce1cecf9',	projectId:'m2-itA',	patchExt:'.zip', hasDoc:true,	version:'1.1', lastVersion:true},
	'm2-itB10':	{crc:'0x46e3ccf2',	projectId:'m2-itB',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm2-itB11':	{crc:'0xe5313a7b',	projectId:'m2-itB',	patchExt:'.zip', hasDoc:true,	version:'1.1'},
	'm2-itB12':	{crc:'0x4eada49f',	projectId:'m2-itB',	patchExt:'.zip', hasDoc:true,	version:'1.2'},
	'm2-itB13':	{crc:'0x2de374fa',	projectId:'m2-itB',	patchExt:'.zip', hasDoc:true,	version:'1.3'},
	'm2-itB145':{crc:'0xa7079c7a',	projectId:'m2-itB',	patchExt:'.zip', hasDoc:true,	version:'1.45'},
	'm2-itB146':{crc:'0xe6dbb3e6',	projectId:'m2-itB',	patchExt:'.zip', hasDoc:true,	version:'1.46'},
	'm2-itB147':{crc:'0x62c04f3f',	projectId:'m2-itB',	patchExt:'.zip', hasDoc:true,	version:'1.47', lastVersion:true},
	'm2-pl100':	{crc:'0xf693cf87',	projectId:'m2-pl',	patchExt:'.zip', hasDoc:true,	version:'1.0.0'},
	'm2-pl102':	{crc:'0xf31c0606',	projectId:'m2-pl',	patchExt:'.zip', hasDoc:true,	version:'1.0.2', lastVersion:true},
	'm2-pt10': 	{crc:'0xa19f1c1c',	projectId:'m2-pt',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
		
	'm12-ja':	{crc:'0x0a44569c',	projectId:'m12-ja'},
	'm12-ko11':	{crc:'0xc0cf1f7e',	projectId:'m12-ko',	patchExt:'.zip', hasDoc:true,	version:'1.1'},
	'm12-de10':	{crc:'0x61a57a10',	projectId:'m12-de',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm12-en101':{crc:'0x7b1ff152',	projectId:'m12-en',	patchExt:'.zip', hasDoc:true,	version:'1.0.1'},
	'm12-fr10':	{crc:'0x4f5af1e5',	projectId:'m12-fr',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm12-it10':	{crc:'0x1e7ab616',	projectId:'m12-it',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm12-pt10':	{crc:'0x3be388bf',	projectId:'m12-pt',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
		
	'm3-ja':	{crc:'0x42ac9cb9',	projectId:'m3-ja'},
	'm3-zh10':	{crc:'0x21fdf96c',	projectId:'m3-zh',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm3-zh10f':	{crc:'0xe2447179',	projectId:'m3-zh',	patchExt:'.zip', hasDoc:true,	version:'1.0+fix', isLatest:true, website:'https://tieba.baidu.com/p/7313315937'},
	'm3-ko10':	{crc:'0x58f58635',	projectId:'m3-ko',	patchExt:'.zip', hasDoc:false,	version:'1.0'},
	'm3-de10':	{crc:'0x9163f829',	projectId:'m3-de',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm3-de11':	{crc:'0xb0b73624',	projectId:'m3-de',	patchExt:'.zip', hasDoc:true,	version:'1.1', isLatest:true},
	'm3-en10':	{crc:'0xd7a5322d',	projectId:'m3-en',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm3-en11':	{crc:'0xede46930',	projectId:'m3-en',	patchExt:'.zip', hasDoc:true,	version:'1.1'},
	'm3-en12':	{crc:'0xa323c029',	projectId:'m3-en',	patchExt:'.zip', hasDoc:true,	version:'1.2'},
	'm3-en13':	{crc:'0x8A3BC5A8',	projectId:'m3-en',	patchExt:'.zip', hasDoc:true,	version:'1.3', isLatest:true},
	'm3-en13f':	{crc:'0x0e013b7b',	projectId:'m3-en',	patchExt:'.zip', hasDoc:true,	version:'1.3+fix',	isLatest:true, website:'https://github.com/Lorenzooone/M3_Eng_1_3/releases'},
	'm3-es10':	{crc:'0x75a955a1',	projectId:'m3-es',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm3-fr10':	{crc:'0xc0cdfcf5',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm3-fr11':	{crc:'0x72000342',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.1'},
	'm3-fr12':	{crc:'0x102d3858',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.2'},
	'm3-fr13':	{crc:'0xd6ce8284',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.3'},
	'm3-fr14':	{crc:'0x1ac32422',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.4'},
	'm3-fr15':	{crc:'0x0d640e05',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.5'},
	'm3-fr16':	{crc:'0x733bc3e5',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.6'},
	'm3-fr17':	{crc:'0x65011f4a',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.7'},
	'm3-fr18':	{crc:'0x76df5b60',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.8'},
	'm3-fr19':	{crc:'0x81429453',	projectId:'m3-fr',	patchExt:'.zip', hasDoc:true,	version:'1.9', isLatest:true},
	'm3-itA10':	{crc:'0xec703e38',	projectId:'m3-it',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm3-itA11':	{crc:'0x58647a26',	projectId:'m3-it',	patchExt:'.zip', hasDoc:true,	version:'1.1'},
	'm3-itA111':{crc:'0xe7185f88',	projectId:'m3-it',	patchExt:'.zip', hasDoc:true,	version:'1.1.1', isLatest:true},
	'm3-itB10':	{crc:'0x7dfea226',	projectId:'m3-it',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm3-nl10':	{crc:'0x8b74324c',	projectId:'m3-nl',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm3-pl10':	{crc:'0xe5911653',	projectId:'m3-pl',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
	'm3-pt10':	{crc:'0x00508b53',	projectId:'m3-pt',	patchExt:'.zip', hasDoc:true,	version:'1.0'},
};*/