var ROM_LIST = {
	'm3-br10':	{crc:"0x00508b53", game:'MOTHER 3', language:'português do Brasil',	version:'1.0',	author:"Earthbound Brasil",	website:"https://www.earthboundbrasil.com",	hasDoc:true, baseRom:"m3-jp", patchExt:'.ups'},
    'm3-cn10':	{crc:"0x21fdf96c", game:'MOTHER 3', language:'中文',			version:'',		author:"",				website:"",										hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-cn11'},
    'm3-cn11':	{crc:"0xe2447179", game:'MOTHER 3', language:'中文',			version:'fixed',author:"",				website:"https://tieba.baidu.com/p/7313315937",	hasDoc:true, baseRom:"m3-jp", patchExt:'.ups'},
    'm3-de10':	{crc:"0x9163f829", game:'MOTHER 3', language:'Deutsch',		version:'1.0',	author:"Madokami",		website:"https://github.com/Madokamiiiiii/Mother3German/releases",	hasDoc:true, baseRom:"m3-jp", patchExt:'.bps', latestVersion:'m3-de11'},
    'm3-de11':	{crc:"0xb0b73624", game:'MOTHER 3', language:'Deutsch',		version:'1.0',	author:"Madokami",		website:"https://github.com/Madokamiiiiii/Mother3German/releases",	hasDoc:true, baseRom:"m3-jp", patchExt:'.bps'},
    'm3-en10':	{crc:"0xd7a5322d", game:'MOTHER 3', language:'English',		version:'1.0',	author:"Tomato",		website:"http://mother3.fobby.net/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-en13'},
    'm3-en11':	{crc:"0xede46930", game:'MOTHER 3', language:'English',		version:'1.1',	author:"Tomato",		website:"http://mother3.fobby.net/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-en13'},
    'm3-en12':	{crc:"0xa323c029", game:'MOTHER 3', language:'English',		version:'1.2',	author:"Tomato",		website:"http://mother3.fobby.net/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-en13'},
    'm3-en13':	{crc:"0x8A3BC5A8", game:'MOTHER 3', language:'English',		version:'1.3',	author:"Tomato",		website:"http://mother3.fobby.net/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups'},
    'm3-es10':	{crc:"0x75a955a1", game:'MOTHER 3', language:'español',		version:'1.0',	author:"Jimmytrius",	website:"http://mother3spanish.blogspot.com/",	hasDoc:true, baseRom:"m3-jp", patchExt:'.ups'},
    'm3-fr10':	{crc:"0xc0cdfcf5", game:'MOTHER 3', language:'français',	version:'1.0',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-fr19'},
    'm3-fr11':	{crc:"0x72000342", game:'MOTHER 3', language:'français',	version:'1.1',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-fr19'},
    'm3-fr12':	{crc:"0x102d3858", game:'MOTHER 3', language:'français',	version:'1.2',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-fr19'},
    'm3-fr13':	{crc:"0xd6ce8284", game:'MOTHER 3', language:'français',	version:'1.3',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-fr19'},
    'm3-fr14':	{crc:"0x1ac32422", game:'MOTHER 3', language:'français',	version:'1.4',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-fr19'},
    'm3-fr15':	{crc:"0x0d640e05", game:'MOTHER 3', language:'français',	version:'1.5',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-fr19'},
    'm3-fr16':	{crc:"0x733bc3e5", game:'MOTHER 3', language:'français',	version:'1.6',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-fr19'},
    'm3-fr17':	{crc:"0x65011f4a", game:'MOTHER 3', language:'français',	version:'1.7',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.zip', latestVersion:'m3-fr19'},
    'm3-fr18':	{crc:"0x76df5b60", game:'MOTHER 3', language:'français',	version:'1.8',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups', latestVersion:'m3-fr19'},
    'm3-fr19':	{crc:"0x81429453", game:'MOTHER 3', language:'français',	version:'1.9',	author:"MotherVF",		website:"http://mother3vf.free.fr/",			hasDoc:true, baseRom:"m3-jp", patchExt:'.ups'},
    'm3-itA10':	{crc:"0x7dfea226", game:'MOTHER 3', language:'italiano',	version:'1.0',	author:"Snifit",		website:"http://snifit.altervista.org/",		hasDoc:true, baseRom:"m3-jp", patchExt:'.ups'},
    'm3-itB11':	{crc:"0xe7185f88", game:'MOTHER 3', language:'italiano',	version:'1.1.1',author:"Lorenzooone",	website:"https://www.romhacking.net/translations/2473/",hasDoc:true,baseRom:"m3-jp", patchExt:'.ups'},
    'm3-jp':	{crc:"0x42ac9cb9", game:'MOTHER 3', language:'日本語'},		
	'm3-kr10':	{crc:"0x58f58635", game:'MOTHER 3', language:'한국어',		version:'1.0',	author:"PJS",			website:"http://blog.naver.com/pjs0493/220392308242",	hasDoc:false,	baseRom:"m3-jp",	patchExt:'.ups'},
    'm3-nl10':	{crc:"0x8b74324c", game:'MOTHER 3', language:'Nederlands',	version:'1.0',	author:"PrismaticAngel",website:"https://www.romhacking.net/translations/5722/",hasDoc:true,	baseRom:"m3-jp",	patchExt:'.xdelta'},
    'm3-pl10':	{crc:"0xe5911653", game:'MOTHER 3', language:'polski',		version:'1.0',	author:"Voxar",			website:"https://www.romhacking.net/translations/6161/",hasDoc:true,	baseRom:"m3-jp",	patchExt:'.xdelta'},
}
